dist: xenial

language: c

compiler:
  - clang
  - gcc

env:
  global:
    - CODECOV_TOKEN="040ce7eb-5bc7-4040-8324-364f3ef4baa3"
    - CFLAGS="-coverage"
  matrix:
    - CONFIGURE_ARGS=-GO3
    - CONFIGURE_ARGS=-EGO3
    - CONFIGURE_ARGS=-HGO3
    - CONFIGURE_ARGS=-RGO3
    - CONFIGURE_ARGS=-SGO3
    - CONFIGURE_ARGS=-EHGO3
    - CONFIGURE_ARGS=-ERGO3
    - CONFIGURE_ARGS=-ESGO3
    - CONFIGURE_ARGS=-HRGO3
    - CONFIGURE_ARGS=-HSGO3
    - CONFIGURE_ARGS=-RSGO3
    - CONFIGURE_ARGS=-EHRGO3
    - CONFIGURE_ARGS=-EHSGO3
    - CONFIGURE_ARGS=-ERSGO3
    - CONFIGURE_ARGS=-HRSGO3
    - CONFIGURE_ARGS=-EHRSGO3

before_install:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./configure.sh "$CONFIGURE_ARGS" && make -j4 && make -j4 test ; fi
