dist: xenial

language: c

arch:
  - amd64
  - ppc64le

compiler:
  - gcc

env:
  global:
    - CODECOV_TOKEN="040ce7eb-5bc7-4040-8324-364f3ef4baa3"
    - CFLAGS="-coverage -DBC_RAND_BUILTIN=0"
  matrix:
    - CONFIGURE_ARGS=-fNPOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-bfNPOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-dfNPOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-fENPOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-bfENPOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-dfENPOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-fNPOg GEN_HOST=1 LONG_BIT=32
    - CONFIGURE_ARGS=-bfNPOg GEN_HOST=1 LONG_BIT=32
    - CONFIGURE_ARGS=-dfNPOg GEN_HOST=1 LONG_BIT=32
    - CONFIGURE_ARGS=-fENPOg GEN_HOST=1 LONG_BIT=32
    - CONFIGURE_ARGS=-bfENPOg GEN_HOST=1 LONG_BIT=32
    - CONFIGURE_ARGS=-dfENPOg GEN_HOST=1 LONG_BIT=32

before_install:
  - sudo apt-get install -y dc expect
  - pip install --user codecov

before_script:
  - curl -o tests/bc/scripts/timeconst.bc https://raw.githubusercontent.com/torvalds/linux/master/kernel/time/timeconst.bc

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./configure.sh "$CONFIGURE_ARGS" && make -j4 && make -j2 test ; fi
