dist: xenial

language: c

compiler:
  - clang
  - gcc

env:
  global:
    - CODECOV_TOKEN="040ce7eb-5bc7-4040-8324-364f3ef4baa3"
    - CFLAGS="-coverage"
  matrix:
    - CONFIGURE_ARGS=-HSOg
    - CONFIGURE_ARGS=-HNSOg
    - CONFIGURE_ARGS=-HRSOg
    - CONFIGURE_ARGS=-HRNSOg
    - CONFIGURE_ARGS=-EHSOg
    - CONFIGURE_ARGS=-EHNSOg
    - CONFIGURE_ARGS=-EHRSOg
    - CONFIGURE_ARGS=-EHNRSOg

before_install:
  - sudo apt-get install -y dc
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./configure.sh "$CONFIGURE_ARGS" && make -j4 && make -j4 test ; fi
