dist: xenial

language: c

compiler:
  - clang
  - gcc

env:
  - CONFIGURE_ARGS=-GOs
  - CONFIGURE_ARGS=-EGOs
  - CONFIGURE_ARGS=-HGOs
  - CONFIGURE_ARGS=-RGOs
  - CONFIGURE_ARGS=-SGOs
  - CONFIGURE_ARGS=-EHGOs
  - CONFIGURE_ARGS=-ERGOs
  - CONFIGURE_ARGS=-ESGOs
  - CONFIGURE_ARGS=-HRGOs
  - CONFIGURE_ARGS=-HSGOs
  - CONFIGURE_ARGS=-RSGOs
  - CONFIGURE_ARGS=-EHRGOs
  - CONFIGURE_ARGS=-EHSGOs
  - CONFIGURE_ARGS=-ERSGOs
  - CONFIGURE_ARGS=-HRSGOs
  - CONFIGURE_ARGS=-EHRSGOs

# command to run tests
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./configure.sh "$CONFIGURE_ARGS" && make -j4 && make -j4 test ; fi
