dist: xenial

language: c

compiler:
  - clang
  - gcc

env:
  - CONFIGURE_ARGS=-Os
  - CONFIGURE_ARGS=-EOs
  - CONFIGURE_ARGS=-HOs
  - CONFIGURE_ARGS=-ROs
  - CONFIGURE_ARGS=-SOs
  - CONFIGURE_ARGS=-EHOs
  - CONFIGURE_ARGS=-EROs
  - CONFIGURE_ARGS=-ESOs
  - CONFIGURE_ARGS=-HROs
  - CONFIGURE_ARGS=-HSOs
  - CONFIGURE_ARGS=-RSOs
  - CONFIGURE_ARGS=-EHROs
  - CONFIGURE_ARGS=-EHSOs
  - CONFIGURE_ARGS=-ERSOs
  - CONFIGURE_ARGS=-HRSOs
  - CONFIGURE_ARGS=-EHRSOs

# command to run tests
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./configure.sh "$CONFIGURE_ARGS" && make -j4 && make -j4 test ; fi
